### ISSUE TITLE
Error Message like this, How to fix it?

### ISSUE THREAD

**Issue by kiriyadee** [travisluong/shadriz#2]
Need to install the following packages:
shadriz@3.0.0
Ok to proceed? (y) y

/Users/enwuft/.npm/_npx/72e0ec61cee2933d/node_modules/shadriz/dist/lib/utils.js:67
const ora_1 = __importDefault(require("ora"));
                              ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/enwuft/.npm/_npx/72e0ec61cee2933d/node_modules/ora/index.js from /Users/enwuft/.npm/_npx/72e0ec61cee2933d/node_modules/shadriz/dist/lib/utils.js not supported.
Instead change the require of index.js in /Users/enwuft/.npm/_npx/72e0ec61cee2933d/node_modules/shadriz/dist/lib/utils.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/enwuft/.npm/_npx/72e0ec61cee2933d/node_modules/shadriz/dist/lib/utils.js:67:31) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v20.17.0

**Comment by travisluong** [comment]
@kiriyadee thanks for reporting this issue. turns out ora requires esm. i went ahead and removed it. things should work now.
